version: '3.8'

x-options:
  &dev-options
  image: prairielearn/prairielearn:local
  ports:
    - 3000:3000
  volumes:
    - ./testCourse:/course
    - /var/run/docker.sock:/var/run/docker.sock
    - ${HOME}/pl_ag_jobs:/jobs
    - .:/PrairieLearn
  container_name: pl
  environment:
    - HOST_JOBS_DIR=${HOME}/pl_ag_jobs
    - NODEMON=true

services:

  build-dev:
    build:
      context: .
    image: prairielearn/prairielearn:local

  # start server on development image
  init: *dev-options
  
  # interactive terminal on development image
  it:
    << : *dev-options
    working_dir: /PrairieLearn
    command: bash