version: '3.8'
services:
  pl:
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    links:
      - pl-db:database
    depends_on: 
      - pl-db
  pl-db:
    container_name: pl-db
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
      - POSTGRES_DB=prairielearn
    volumes:
        - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres:

networks:
  default: