site_name: PrairieLearn
site_url: https://github.com/PrairieLearn/PrairieLearn
repo_url: https://github.com/PrairieLearn/PrairieLearn
theme: readthedocs
docs_dir: new_docs
# Fix "Edit on GitHub" link: (defaults to edit/master/docs/, note the s)
edit_uri: blob/master/docs/

extra_javascript:
  - mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

pages:
- Introduction:
  - 'What is PrairieLearn?': 'index.md'
  - 'News': 'news_items.md'

- Instructor Manual:
  - Get Started:
    - 'Requesting your course space': 'Instructor/GetStarted/requestCourse.md'
    - 'Creating course content': 'Instructor/GetStarted/getStarted.md'
    - 'Question Gallery': 'Instructor/GetStarted/questionGallery.md'
    - 'Workshops': 'workshop/index.md'
  - How-to Guides:
    - 'Assessments': 'Instructor/HowTos/howtoAssessments.md'


- Student Manual:
  - Get Started:
    - 'Addding a course': 'addCourse.md'

- Student Manual:
  - Get Started:
    - 'Adding a course': 'addCourse.md'

- Developers Manual:
  - Get Started:
    - 'PL architecture': 'makeCourse.md'

- Administrative Manual:
  - Get Started:
    - 'Creating a course': 'makeCourse.md'
