site_name: PrairieLearn
site_url: https://github.com/PrairieLearn/PrairieLearn
repo_url: https://github.com/PrairieLearn/PrairieLearn
theme: readthedocs
docs_dir: new_docs
# Fix "Edit on GitHub" link: (defaults to edit/master/docs/, note the s)
edit_uri: blob/master/docs/

extra_javascript:
  - mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

pages:
- Introduction:
  - 'What is PrairieLearn?': 'index.md'
  - 'News': 'news_items.md'

- Instructor Manual:
  - Get Started:
    - 'Request your course space': 'requestCourse.md'
    - 'Creating content in the browser': 'getStarted.md'
    - 'Workshop': 'workshop/index.md'
  - How-to Guides:
    - 'Requesting your course space': 'requestCourse.md'
    - 'Creating content in the browser': 'getStarted.md'
    - 'Workshop': 'workshop/index.md'
