name: CI

on: [push, pull_request]

jobs:
  build-base-image:
    name: Build prairielearn/plbase image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the plbase docker image if needed
        run: sh ./tools/build-plbase-if-needed.sh

  build:
    name: Build and test
    needs: build-base-image
    runs-on: ubuntu-latest

    steps:
      - name: Build the testing docker image
        run: docker build -t pltest .
      - name: Start the container
        run: docker run -td --name=test_container pltest /bin/bash
      - name: Run the JavaScript linter
        run: docker exec test_container /PrairieLearn/docker/lint_js.sh
      - name: Run the Python linter
        run: docker exec test_container /PrairieLearn/docker/lint_python.sh
      - name: Run typechecker
        run: docker exec test_container /PrairieLearn/docker/typecheck.sh
      - name: Run the PrairieLib tests
        run: docker exec test_container /PrairieLearn/docker/test_prairielib.sh
      - name: Run the grader_host tests
        run: docker exec test_container /PrairieLearn/docker/test_grader_host.sh
      - name: Run the JavaScript tests
        run: docker exec test_container /PrairieLearn/docker/test_js.sh
      - name: Run the Python tests
        run: docker exec test_container /PrairieLearn/docker/test_python.sh
      - name: Copy code-coverage data out of container
        run: docker cp test_container:/PrairieLearn/coverage coverage
      - name: Directory listing for debug
        run: ls -lR
      - name: Head of lcov.info for debug
        run: head -1000 coverage/lcov.info
      - name: Send code-coverage data to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
        continue-on-error: true

  build-executor:
    name: Build prairielearn/executor image
    needs: build-base-image
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies on host
        run: npm ci
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build executor image
        run: ./tools/executor/build.js
      - name: Push executor image to registries
        run: ./tools/executor/release.js

